type Source {
  title: String
  description: String
  url: String
}

input SourceInput {
  title: String
  description: String
  url: String
}

type Query {
  sources: [Source]
}

type Mutation {
  createSource(source: SourceInput): Source
}
